[project]
name = "arch-linux-news-tg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "dotenv>=0.9.9",
    "feedparser>=6.0.12",
    "html-to-markdown>=2.9.2",
    "translate>=3.8.0",
]
